exit_code: 1
args: tests/fixtures/async_error.ts --reload
output: tests/outputs/async_error.ts.out
