running 1 test from ./main.js
throws ... FAILED (1ms)

 ERRORS 

throws => ./main.js:1:6
error: Error: Throws
  throw new Error("Throws");
        ^
    at throws ([WILDCARD]/main.js:5:9)

 FAILURES 

throws => ./main.js:1:6

FAILED | 0 passed | 1 failed (5ms)

error: Test failed
